### PR TITLE
Refactor dtcs into a ecu->dtc_list table of tables, move them out into separate files

### PR DESCRIPTION
**Pull request by brendandburns**
@aaeegg @fenugrec 

This is the first step as discussed in #95 

I have refactored the existing codes/codebase to make the table of tables and prepare for different lists of dtcs.

There should be no actual changes in functionality.

Please let me know if there's any feedback or changes to the approach desired.

### CODE REVIEW

**Comment by fenugrec** [comment]
Just skimming the code in less than 5 minutes (will need to take a closer look later), I think you're on the right track.

Some notes; many struct members should be marked `const`, such as

- printable strings should be `const char *`
- ptr to DTC table should be `const struct XYZ *`
- table, and table of tables, should also be const (I didn't notice if they already are, ignore this comment if so )

also, make sure you've run our uncrustify.cfg formatter prior to committing. I didn't check if your 'formatting' commit applies to existing code, or stuff you just added.

Commit message also need a bit of work, see how previous messages are formatted.

**Comment by brendandburns** [comment]
Just so I'm clear, the current structs for ECU:
https://github.com/fenugrec/freediag/blob/master/scantool/scantool_850.c#L57

And DTC:
https://github.com/fenugrec/freediag/blob/master/scantool/scantool_850.c#L95

Have printable strings which are `char*` not `const char*`

I don't mind making them const in this PR (or a separate PR) but I wanted to make sure that was the desired intent.

Let me know what you prefer.

I will refactor the table of tables to be "unpacked" as you suggest.

**Comment by aaeegg** [comment]
The strings aren't going to be modified during execution, so they should have the const qualifier so the compiler knows to put them in the rodata section and apply appropriate optimizations. I snuck the omission past fenugrec but you weren't so lucky.

As long as you're making tweaks - freediag uses C-style comments in some places and C++-style comments elsewhere, but the new comment in dtc_raw_by_printable should be C-style to match the surrounding code.

**Comment by fenugrec** [comment]
> I don't mind making them const in this PR

Thanks, I just took care of it (as well as some other unrelated, low-hanging fruit in scantool_850.c flagged by cppcheck)

**Comment by brendandburns** [comment]
Ok, rebased and I think I addressed all of your comments.

I also ran `uncrustify` on `scantool_850.c` which resulted in some unrelated changes. Let me know if you'd prefer those in a separate PR.

Please take another look when you get a chance.

**Comment by fenugrec** [comment]
Merged (reworded commit message) as of #8aabe66c834230e7152f9c066cd20428b289e165

Also reorganized code and functions, I'm not fan of having a struct definition in a basic.h.
I split DTC and ECU lists in separate files, thinking they may evolve independantly, but I don't mind re-merging them if you guys want to eliminate the `ecu_dtc_map` array; its sole interesting member `const struct dtc_table_entry *dtc_table;` could just be moved to struct `ecu_info`  ?

**Comment by fenugrec** [comment]
Oops, I should've looked at your PR #99  first. Some of the changes I made make less sense. Let me know if anything needs be reverted / changed to not completely break your code generators .

**Pull request closed without merging**
